version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: wms_mysql
    restart: unless-stopped
    #command: --skip-grant-tables # THIS IS TEMPORARY DEBUG, REMOVE THIS BEFORE DEPLOYMENT
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: inventory_root_pass
      MYSQL_PASSWORD: inventory_pass
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
    volumes:
      - wms_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wms_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: inventory_user
      PMA_PASSWORD: inventory_pass
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"

  app:
    build:
      context: ..
      dockerfile: docker_wms/Dockerfile.cli
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wms_user
      DB_PASS: wms_pass
      DB_NAME: wms_demo
    depends_on:
      - db
    stdin_open: true
    tty: true

  web:
    build:
      context: ..
      dockerfile: docker_wms/Dockerfile.web
    environment:
      DJANGO_SETTINGS_MODULE: wms_project.settings
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wms_user
      DB_PASS: wms_pass
      DB_NAME: wms_demo
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  wms_mysql_data: