services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wms_demo
      MYSQL_USER: wms_user
      MYSQL_PASSWORD: wms_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker_wms/Dockerfile.cli
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wms_user
      DB_PASS: wms_pass
      DB_NAME: wms_demo
    depends_on:
      - db
    stdin_open: true
    tty: true

  web:
    build:
      context: ..
      dockerfile: docker_wms/Dockerfile.web
    environment:
      DJANGO_SETTINGS_MODULE: wms_project.settings
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wms_user
      DB_PASS: wms_pass
      DB_NAME: wms_demo
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
