FROM python:3.10-slim
WORKDIR /app

# Install system dependencies for mysqlclient and pkg-config
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        default-libmysqlclient-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir mysqlclient gunicorn

# Copy project code
COPY ../database ./database
COPY ../src      ./src

# Collect static (if any)
WORKDIR /app/database
RUN python manage.py collectstatic --noinput

# Run the web service
ENTRYPOINT ["gunicorn", "wms_project.wsgi:application", "--bind", "0.0.0.0:8000"]