# Generated by Django 5.2.4 on 2025-07-28 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeevent',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', editable=False, help_text='Shift at time of event', max_length=10),
        ),
        migrations.AddField(
            model_name='barcodeevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barcodeevent',
            name='source',
            field=models.CharField(choices=[('scan', 'Scan'), ('manual', 'Manual'), ('gen', 'Generated')], max_length=10),
        ),
        migrations.CreateModel(
            name='DailyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('users', models.ManyToManyField(related_name='rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
    ]
