# Generated by Django 5.2.4 on 2025-08-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200)),
                ('item_name', models.CharField(max_length=255)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, max_length=200)),
                ('organic', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('satuan', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, max_length=200)),
                ('organic', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='scanner.itemin')),
            ],
        ),
    ]
